---
- name: Restart Chrony
  ansible.builtin.systemd:
    name: chronyd
    state: restarted

- name: Reload NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: reloaded

- name: Reload udev
  ansible.builtin.command: udevadm control --reload-rules
  register: udev_output
  changed_when: true

- name: Update Grub
  ansible.builtin.command: update-grub
  register: grub_output
  changed_when: true
  notify: Reboot OS

- name: Reboot OS
  ansible.builtin.reboot:
    reboot_timeout: 3600
