---
- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: true

- name: Check if a reboot is needed
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot and cleanup server
  when: reboot_required_file.stat.exists
  block:
    - name: Reboot Server if Necessary
      ansible.builtin.reboot:
        reboot_timeout: 3600

    - name: Cleanup post reboot
      ansible.builtin.apt:
        autoremove: true

- name: Cleanup rPI servers
  when: ansible_architecture == 'aarch64'
  block:
    - name: Find backup firmware files
      ansible.builtin.find:
        paths: "/boot/firmware"
        file_type: file
        patterns: '*.bak'
      register: firmware_list

    - name: Cleanup backup firmware files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items:
        - "{{ firmware_list.files }}"
      loop_control:
        label: "{{ item.path }}"
