---
# this is required for needs-restarting
- name: Install Pre-reqs
  ansible.builtin.package:
    name:
      - yum-utils

- name: Upgrade packages via yum
  ansible.builtin.yum:
    name: '*'
    state: 'latest' # noqa package-latest
  when:
    - (ansible_facts['distribution_major_version'] == '6') or
      (ansible_facts['distribution_major_version'] == '7')

- name: Upgrade packages via dnf
  ansible.builtin.dnf:
    name: '*'
    state: 'latest'  # noqa package-latest
  when:
    - ansible_facts['distribution_major_version'] >= '8'

- name: Check to see if we need a reboot
  ansible.builtin.command: needs-restarting -r
  changed_when: false
  failed_when: ( result.rc not in  [ 0, 1 ] )
  register: result

- name: Reboot server if necessary
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: result.rc >= 1
  throttle: 1

- name: Run cleanups
  ansible.builtin.command: yum clean all
  changed_when: true
