---
- name: Disable IPv6 via sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  when:
    - ansible_os_family != "Debian"

# Without removing these, anything that uses sysctl will throw errors down the line
- name: Remove soon to be dead IPv6 entries sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    state: absent
    reload: true
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
    - net.ipv6.bindv6only
  when:
    - ansible_os_family == "Debian"

# This is needed due to Ubuntu 22.04 and VMWare
- name: Disable IPv6 at boot
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regex: "{{ item }}="
    line: "{{ item }}=\"ipv6.disable=1\""
  loop:
    - GRUB_CMDLINE_LINUX_DEFAULT
    - GRUB_CMDLINE_LINUX
  notify: Update Grub
  when:
    - ansible_os_family == "Debian"
