---
- name: Set 'dns=none' in Network Manager
  community.general.ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: true
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: "0644"
    backup: true
  when:
    - ansible_os_family == "RedHat"
  notify: Reload NetworkManager

- name: Deploy resolv.conf template
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
