---
- name: Set timezone to US/Central
  community.general.timezone:
    name: US/Central

- name: Install Chrony
  ansible.builtin.package:
    name:
      - chrony

- name: Deploy Chrony Config
  ansible.builtin.copy:
    src: chrony.conf
    dest: "{{ chrony_conf_location }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart Chrony

- name: Start/Enable Chrony
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: true
