---
- name: Enable IOMMU
  ansible.builtin.lineinfile:
    path: /etc/kernel/cmdline
    regex: '^(root=ZFS=rpool/ROOT/pve-1 boot=zfs)(?:(?!iommu=on).)*?$'
    line: '\1 iommu=on'
    backup: true
    backrefs: true
  notify:
    - Refresh EFI
    - Reboot Proxmox

- name: Add vfio modules
  ansible.builtin.lineinfile:
    path: /etc/modules
    regex: "^{{ item }}$"
    line: "{{ item }}"
  with_items:
    - vfio
    - vfio_iommu_type1
    - vfio_pci
  notify:
    - Update InitramFS
    - Reboot Proxmox

- name: Trigger nVidia card fix
  community.general.modprobe:
    name: kvm
    state: present
    params: 'ignore_msrs=1 report_ignored_msrs=0'
    persistent: present

- name: Get nVidia PCI Info
  ansible.builtin.shell: set -o pipefail | lspci -nn | grep 'NVIDIA'
  changed_when: false
  register: nvidia_pci

- name: Build search string
  ansible.builtin.set_fact:
    search_string: '\[(.{4}:.{4})]'

- name: Build vfio string
  ansible.builtin.set_fact:
    vfio_pci: "{{ vfio_pci | default('') + item | regex_search(search_string) | replace('[', '') | replace(']', '') + ',' }}"
  with_items:
    - "{{ nvidia_pci.stdout_lines }}"

- name: Trim last comma
  ansible.builtin.set_fact:
    vfio_pci: "{{ vfio_pci[:-1] }}"

- name: Add vfio PCI IDs
  community.general.modprobe:
    name: vfio-pci
    state: present
    params: "ids={{ vfio_pci }}"
    persistent: present
  notify:
    - Reboot Proxmox

- name: Blacklist nVidia drivers
  community.general.kernel_blacklist:
    blacklist_file: /etc/modprobe.d/blacklist.conf
    name: "{{ item }}"
    state: present
  loop:
    - nouveau
    - nvidia
    - nvidiafb
    - nvidia_drm
  notify:
    - Reboot Proxmox

- name: Trigger all the pending notifies
  ansible.builtin.meta: flush_handlers

- name: Gather dmesg
  ansible.builtin.command: dmesg
  changed_when: false
  register: dmesg_out

- name: Verify dmesg lines
  ansible.builtin.assert:
    that:
      - "'Detected AMD IOMMU #0' in dmesg_out.stdout"
      - "'AMD-Vi: Interrupt remapping enabled' in dmesg_out.stdout"
      - "'vgaarb: deactivate vga console' in dmesg_out.stdout"
